### ISSUE TITLE
mapping spans to relations

### ISSUE THREAD

**Issue by ghost** [NLPbox/codra-docker#2]
Hello , 
I am just wondering if there is an easy way to navigate the tree and extract the corresponding relation when given two spans. Also where to find the spans of the parsed text?
I really appreciate your time

Thank you

**Comment by arne-cl** [comment]
Dear @moh55m55,

can you give a concrete example, i.e. the input you give to CODRA, the output you get and the output you would like to have?

Best regards,
Arne

**Comment by ghost** [comment]
Thank you, 
I was able to navigate the tree and extract the relations. 
Thanks again for providing this image
