### ISSUE TITLE
Error :cPickle.UnpicklingError: invalid load key, 'v'. 

### ISSUE THREAD

**Issue by Julinear** [NLPbox/codra-docker#4]
When I run "Discourses_Segementer.py", it occurs the problem like this:
![a](https://user-images.githubusercontent.com/33052315/51177824-b68c0b80-18fb-11e9-8bba-1169be171e3d.png)
An error occurs when the program executes to function LoadData.
![b](https://user-images.githubusercontent.com/33052315/51178455-8c3b4d80-18fd-11e9-93e1-c8a0eb066a5d.png)
The  filename is "PT_POS_TAGS",and the content of file is like this:
![c](https://user-images.githubusercontent.com/33052315/51179811-8a738900-1901-11e9-916c-109a760b3d58.png)
 how to solve the problem?

**Comment by arne-cl** [comment]
Dear @Julinear,
it looks like you're trying to run an old version of this repo (that still used git-lfs,
which never properly worked for me).

Can you please update your repo with "git pull" or git clone a new copy and
build and run the repo like it is described in the README?

**Comment by Julinear** [comment]
Really thanks for your reply. I'm sorry for that I push the issue on the wrong project. This problem is connected with your another project named "codra-rst-discourse".
By the way, can this project achieve the sentence segmentation. 
![image](https://user-images.githubusercontent.com/33052315/51219076-29cc6680-196a-11e9-95ea-f8c9f6dca878.png)
And  is this the clause sentence?
![image](https://user-images.githubusercontent.com/33052315/51219107-4cf71600-196a-11e9-871e-800049cd1561.png)

**Comment by arne-cl** [comment]
Dear @Julinear,

no, CODRA only does EDU segmentation and RST trees itself. For sentence segmentation, it uses
the Charniak parser, for which I've also created a [Dockerfile](https://github.com/NLPbox/charniak-docker.git).

The "clauses" in your example output are the parts of a rhetorical relation (either one nucleus and one satellite or multiple nucleii).
